### ISSUE TITLE
Question, what is this plugin for?

### ISSUE THREAD

**Issue by brenwell** [webpack/karma-webpack#39]
Hey there,

this may seem like I stupid question, but I am having a hard time getting Karma to work with my webpack based application. I am trying to `require` files in my tests, however all the aliases in my webpack config do not resolve. I can't seem to find a description of what this plugin does and I was hoping that this plugin resolves aliases, is this correct?

>
It may be worth noting that I am not using the webpack dev server as I required a custom solution and am using koa

Thanks in advance

**Comment by sokra** [comment]
This compiles the karma tests with webpack before running them.

You need the resolve config in your karma.config.js (as described by the README). (use `require("./webpack.config.js")` in `karma.config.js`.

**Comment by brenwell** [comment]
Great, I will check it out, thanks for the reply

**Comment by ColCh** [comment]
@sokra that means it can be used with *jest* too? not tested yet

**Comment by petrbela** [comment]
@ColCh if you're using jest with karma then it should work

**Comment by hankthewhale** [comment]
I hate to resurrect this issue but because it's still open, I'll piggy back on it instead of creating a new one. My aliases that are resolving in my dev/prod configs are not resolving in the karma.config.

Here's what the webpack entry looks like in `karma.config.js`

```js
    webpack: {
      devtool: 'inline-source-map',
      resolve: {
        modules: [
          'node_modules',
          '.src/client'
        ],
        modulesDirectories: [
          'node_modules',
          '.src/client'
        ],
        extensions: ['', '.js', '.jsx'],
        alias: {
          'sinon': 'sinon/pkg/sinon',
          __app_core:      './src/client/app_core',
          __shared_styles: './src/client/shared_styles',
          __main_dir     : './src/client'
        }
      },
      module: {
        noParse: [
          /node_modules\/sinon\//
        ],
        loaders: [
          {
            test: /\.js?$/,
            exclude: /node_modules/,
            loader: 'babel'
          },
        ],
      },
      externals: {
        'jsdom': 'window',
        'cheerio': 'window',
        'react/lib/ExecutionEnvironment': true,
        'react/lib/ReactContext': 'window'
      }
    }

```

Notice `webpack.resolve.alias`? When running karam, I encounter...

```
Error: Cannot find module "__main_dir/components/views/Home"
```

It doesn't even look like it's processing `__main_dir` and it treating it as if my directory is named `__main_dir`. I logged out info in index.js and it seems like it's being read in correctly but I am a bit confused by something. What does `this-compilation` do? It doesn't appear to be used anywhere within the project but the compiled webpack options appear to want to use it.

I'm still digging but any insight as to why my aliases are not resolving would be helpful! Again, these same aliases are resolving just fine with dev/prod webpack configs.

**Comment by d3viant0ne** [comment]
@hankthewhale

1.) Throw that in a new issue
2.) A minimal example will make this far easier to work out

**Comment by hankthewhale** [comment]
@d3viant0ne sounds great. I usually would create a new issue but because it was still open, I piggy-backed.

Creating a new one now. Thanks for the response.

**Comment by aghreed** [comment]
@hankthewhale did you ever create a new issue? I can't seem to find it if you did... I'm also having issues with webpack alias files not being found when running karma, but they are when running webpack standalone.

**Comment by MikaAK** [comment]
@aghreed #168
